baseURL = 'https://wilsonlaiwx.github.io/whitehelmetdev.github.io/'
languageCode = 'en-us'
title = "Wilson's Portfolio"
theme = "basic"
[params]
  author = "Wilson Lai"
  description = "My Portfolio Site"