baseURL = 'http://example.org/'
languageCode = 'en-us'
title = "Wilson's Portfolio"
googleAnalytics = "UA-xxxxxxxxxxxx"
theme = "basic"
[params]
  author = "Wilson Lai"
  description = "My Portfolio Site"